# fly.toml app configuration file generated for mirror-ng on 2026-05-21T12:37:40Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mirror-ng'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  DB_PATH = '/app/data/mirror.db'
  MODEL_PATH = '/app/data/category_model.pkl'
  DATABASE_URL = 'sqlite:///./data/mirror.db'
  DEBUG = 'false'
  FORWARDED_ALLOW_IPS = '::1,fd00::/8,10.0.0.0/8'
  ENVIRONMENT = 'production'

[[mounts]]
  source = 'mirror_data'
  destination = '/app/data'

[http_service]
  internal_port = 7860
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
